---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01f7bxmqd0dz39ytngcn94xh5x"
    - from: "jfmd@*"
      to: "jfmd@01f7bxmrqwj4d6qcvhz8mqq6aw"
    - from: "jfevt@*"
      to: "jfevt@01f7bxmgq0p92s0h4akgw40w65"
schema-version: 2
